### ISSUE TITLE
how do i set  unity 2019.4.14f1 ???

### ISSUE THREAD

**Issue by jungmoona** [googlevr/cardboard-xr-plugin#15]
i have question  
Deprecated "XR Settings settings"
i dont set this
```
XR Plug-in Management Settings
Navigate to Project Settings > XR Plug-in Management.

Select Cardboard XR Plugin under Plug-in Providers.
```

https://developers.google.com/cardboard/develop/unity/quickstart

how do i set Cardboard XR ?

**Comment by jballoffet** [comment]
As indicated in #1, please file issues at https://github.com/googlevr/cardboard/issues. About your question, it seems to me that you're trying to set the XR Plugin in "Project Settings > Player > XR Settings" (which is a deprecated option) instead of "Project Settings > XR Plug-in Management". In case you don't have that option in Project Settings, please double check in the Package Manager that com.unity.xr.management v3.2.9 or higher is currently installed. I'm closing this issue, in case you still need more help, please open a new issue at https://github.com/googlevr/cardboard/issues.
